Check for correct context shutdown
ros2/rmw_fastrtps pull request #486
Opened 2020-11-17 16:56 UTC by imontesino

Added checks for the creation of nodes in context which has been shutdown, and for shutdown of a context with active nodes. 

Thess throw a `RMW_RET_ERROR` instead of causing segfaults as seen in ros2/rmw_fastrtps#478

Signed-off-by: Ignacio Montesino <ignaciomontesino@eprosima.com>

2020-11-18 07:36 UTC, EduPonz commented
@ivanpauno Can you take a look at this in relation with https://github.com/ros2/rmw_fastrtps/issues/478#issuecomment-724788134?

2020-11-18 14:29 UTC, ivanpauno requested changes
The issue isn't `rmw_shutdown` but ``rmw_context_fini`.
Shutdown is a flag that doesn't clean any resource, and it's safe to call it will a node created from that context is alive.

The issue is calling `rmw_context_fini()` when not all of its node have been destroyed.

2020-11-18 15:58 UTC, EduPonz commented
What we understood from https://github.com/ros2/rmw_fastrtps/blob/master/rmw_fastrtps_cpp/src/rmw_init.cpp#L154-L157 is that `rmw_context_fini()` checks whether the context has been shutdown, and so I thought that the nodes' destruction was a pre-condition for `rmw_shutdown()`. If that is not the case, then we'll update this PR accordingly

2020-11-18 16:39 UTC, ivanpauno commented
> What we understood from https://github.com/ros2/rmw_fastrtps/blob/master/rmw_fastrtps_cpp/src/rmw_init.cpp#L154-L157 is that rmw_context_fini() checks whether the context has been shutdown, and so I thought that the nodes' destruction was a pre-condition for rmw_shutdown(). If that is not the case, then we'll update this PR accordingly

Context shutdown is a precondition for context fini, but not for node fini.
All node finis are a precondition of the parent context fini.

2020-11-18 16:40 UTC, ivanpauno commented
To be more clear, context shutdown at rmw level is actually "doing nothing", so it cannot cause an use after free as reported in #478.

2020-11-20 11:23 UTC, EduPonz commented
@ivanpauno , could you take a look at this?

2020-11-30 14:27 UTC, ivanpauno approved these changes

2020-11-30 14:27 UTC, ivanpauno commented on rmw_fastrtps_cpp/src/rmw_init.cpp
> +    RMW_SET_ERROR_MSG("Deleting a context with active nodes");
nitpick^N:
```suggestion
    RMW_SET_ERROR_MSG("Finalizing a context with active nodes");
```

2020-11-30 14:27 UTC, ivanpauno commented on rmw_fastrtps_dynamic_cpp/src/rmw_init.cpp
> +    RMW_SET_ERROR_MSG("Deleting a context with active nodes");
```suggestion
    RMW_SET_ERROR_MSG("Finalizing a context with active nodes");
```

2020-11-30 14:33 UTC, ivanpauno commented
CI:

* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=13177)](http://ci.ros2.org/job/ci_linux/13177/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=8108)](http://ci.ros2.org/job/ci_linux-aarch64/8108/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=10893)](http://ci.ros2.org/job/ci_osx/10893/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=13191)](http://ci.ros2.org/job/ci_windows/13191/)

2020-11-30 17:50 UTC, ivanpauno commented
@imontesino can you check the macos failures?
The windows warnings don't seem to be related.

2020-12-03 20:23 UTC, jacobperron commented
The macOS errors have been occurring a little while now. See https://github.com/ros2/rmw_fastrtps/issues/491.

2020-12-03 20:24 UTC, jacobperron approved these changes

2020-12-03 20:33 UTC, merged