Call callbacks only if unread count > 0
ros2/rmw_fastrtps pull request #634
Opened 2022-09-22 09:45 UTC by mauropasse

Listener callbacks for QoS events were being called when assigned.

They should be called here only if there were previous events before setting these callbacks.

This PR checks the `total_count_change` for each event, and if greater than zero, call the corresponding callback.

Signed-off-by: Mauro Passerino <mpasserino@irobot.com>

2022-09-22 11:02 UTC, MiguelCompany requested changes
Looks good, but linter errors should be fixed first.

2022-09-22 17:54 UTC, fujitatomoya approved these changes
lgtm

2022-09-22 17:57 UTC, fujitatomoya commented
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=17361)](http://ci.ros2.org/job/ci_linux/17361/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=11895)](http://ci.ros2.org/job/ci_linux-aarch64/11895/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=17861)](http://ci.ros2.org/job/ci_windows/17861/)

2022-09-28 19:18 UTC, clalancette commented
Green CI and approved, so merging.

2022-09-28 19:18 UTC, merged

2022-09-28 21:47 UTC, fujitatomoya commented
@mergifyio backport humble