Use unique mangled names when creating Content Filter Topics
ros2/rmw_fastrtps pull request #762
Opened 2024-05-30 10:04 UTC by Mario-DL

This PR makes every Content Filter Name unique by adding a static atomic counter.
Related PRs
* 
*

2024-05-30 10:34 UTC, ahcorde requested changes
Check linters `cpplint` and `uncrustify`

2024-05-30 10:34 UTC, ahcorde commented on rmw_fastrtps_shared_cpp/src/utils.cpp
> +  static std::atomic<uint32_t> cft_counter{0};
include `<atomic>` and `<cstdint>`

2024-05-31 21:39 UTC, fujitatomoya commented
@Mario-DL thanks for the PR.

i would like to clarify that,

> This PR makes every Content Filter Name unique by adding a static atomic counter. With this change, two or more content-filtered subscriptions can be created for the same topic name.

before this fix, we cannot have the content filtered topic on the topic within the same participant, correct? and that is the problem to address with this PR?

2024-06-01 14:45 UTC, fujitatomoya approved these changes
lgtm with green CI.

I would like to ask someone from eProsima to review this.

CC: @MiguelCompany @EduPonz

2024-06-03 05:27 UTC, MiguelCompany commented
> before this fix, we cannot have the content filtered topic on the topic within the same participant, correct? and that is the problem to address with this PR?

Before this fix, we cannot have more than one content filter on the same topic within the same participant. Correct.

> I would like to ask someone from eProsima to review this.

We already did, since @Mario-DL works at eProsima. See my approval [here](https://github.com/eProsima/rmw_fastrtps/pull/29#pullrequestreview-2084865854)

2024-06-03 08:33 UTC, ahcorde commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21200)](http://ci.ros2.org/job/ci_linux/21200/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=15510)](http://ci.ros2.org/job/ci_linux-aarch64/15510/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=21922)](http://ci.ros2.org/job/ci_windows/21922/)

2024-06-03 16:05 UTC, ahcorde commented
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=21204)](http://ci.ros2.org/job/ci_linux/21204/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=15514)](http://ci.ros2.org/job/ci_linux-aarch64/15514/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=21926)](http://ci.ros2.org/job/ci_windows/21926/)

2024-06-03 17:02 UTC, ahcorde approved these changes

2024-06-03 17:02 UTC, merged

2024-06-03 17:25 UTC, fujitatomoya commented
@ahcorde thanks for taking care of CI.

@Mario-DL @MiguelCompany how does it sound that we backport this to `jazzy`, `iron` and `humble`? since this is just adding the static local variable in function scope, it is okay to backport and user-experience is better? if okay, i will manage all backports including CI. what do you think?

2024-06-03 19:30 UTC, MiguelCompany commented
> how does it sound that we backport this to `jazzy`, `iron` and `humble`?

@fujitatomoya it sounds great. I think it makes sense to backport

2024-06-05 21:16 UTC, fujitatomoya commented
@Mergifyio backport iron humble jazzy

2024-06-12 01:20 UTC, fujitatomoya commented
@Mario-DL @MiguelCompany Just FYI, all backports up to humble completed.

2024-06-12 06:38 UTC, MiguelCompany commented
> Just FYI, all backports up to humble completed.

Thank you very much @fujitatomoya !